import type { ItemV2 } from "./types";
export const items: ItemV2[] = [    {
        id: "crop",
        name: "Crop",
        itemType: "crop",
        width: 1,
        height: 1,
        placement: "block",
        color: "#b38f1f",
        icon: "🌱",
    },

    {
        id: "sprinkler-9x9",
        name: "9×9 Sprinkler",
        itemType: "sprinkler",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 4,
        color: "#1e40af",
        icon: "💧",
    },    {
        id: "sprinkler-5x5",
        name: "5×5 Sprinkler",
        itemType: "sprinkler",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 2,
        color: "#2563eb",
        icon: "💧",
    },    {
        id: "sprinkler-3x3",
        name: "3×3 Sprinkler",
        itemType: "sprinkler",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 1,
        color: "#3b82f6",
        icon: "💧",
    },

    {
        id: "tree-2x2",
        name: "2×2 Tree",
        itemType: "tree",
        width: 2,
        height: 2,
        placement: "block",
        color: "#166534",
        icon: "🌳",
    },    {
        id: "tree-5x5",
        name: "5×5 Tree",
        itemType: "tree",
        width: 5,
        height: 5,
        placement: "block",
        color: "#14532d",
        icon: "🌳",
    },

    {
        id: "scarecrow-11x11",
        name: "11×11 Scarecrow",
        itemType: "scarecrow",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 5,
        color: "#a16207",
        icon: "🧑‍🌾",
    },    {
        id: "scarecrow-5x5",
        name: "5×5 Scarecrow",
        itemType: "scarecrow",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 2,
        color: "#854d0e",
        icon: "🧑‍🌾",
    },    {
        id: "scarecrow-ultimate",
        name: "Ultimate Scarecrow",
        itemType: "scarecrow",
        width: 1,
        height: 1,
        placement: "radius",
        radius: 9,
        color: "#b45309",
        icon: "🧑‍🌾",
    },

    {
        id: "machine-1",
        name: "Machine 1×1",
        itemType: "machine",
        width: 1,
        height: 1,
        placement: "block",
        color: "#4b5563",
        icon: "⚙️",
    },    {
        id: "machine-2",
        name: "Machine 2×2",
        itemType: "machine",
        width: 2,
        height: 2,
        placement: "block",
        color: "#1f2937",
        icon: "⚙️",
    },

    {
        id: "path-stone",
        name: "Path",
        itemType: "other",
        width: 1,
        height: 1,
        placement: "block",
        color: "#6b7280",
        icon: "⬜",
    },    {
        id: "path-dead-green",
        name: "Path",
        itemType: "other",
        width: 1,
        height: 1,
        placement: "block",
        color: "#4b5563",
        icon: "🟫",
    },    {
        id: "path-wood-green",
        name: "Path",
        itemType: "other",
        width: 1,
        height: 1,
        placement: "block",
        color: "#3f6212",
        icon: "🟩",
    },
    {
        id: "fence-1",
        name: "Fence",
        itemType: "other",
        width: 1,
        height: 1,
        placement: "block",
        color: "#78350f",
        icon: "⎶",
    },
    {
        id: "arches-1x3",
        name: "Arch 1×3",
        itemType: "other",
        width: 1,
        height: 3,
        placement: "block",
        color: "#14532d",
        icon: "∩",
    },    {
        id: "arches-3x1",
        name: "Arch 3×1",
        itemType: "other",
        width: 3,
        height: 1,
        placement: "block",
        color: "#14532d",
        icon: "∩",
    },

    {
        id: "mushroom-log-2x2",
        name: "Mushroom Log",
        itemType: "other",
        width: 2,
        height: 2,
        placement: "block",
        color: "#15803d",
        icon: "🍄",
    },    {
        id: "beehive-2x2",
        name: "Beehive",
        itemType: "machine",
        width: 2,
        height: 2,
        placement: "block",
        color: "#b45309",
        icon: "🐝",
    },

    {
        id: "barn-8x5",
        name: "Barn",
        itemType: "building",
        width: 8,
        height: 5,
        placement: "block",
        color: "#7c2d12",
        icon: "🐮",
    },    {
        id: "coop-7x4",
        name: "Coop",
        itemType: "building",
        width: 7,
        height: 4,
        placement: "block",
        color: "#b45309",
        icon: "🐔",
    },    {
        id: "stable-5x3",
        name: "Stable",
        itemType: "building",
        width: 5,
        height: 3,
        placement: "block",
        color: "#78350f",
        icon: "🐴",
    },    {
        id: "silo-3x3",
        name: "Silo",
        itemType: "building",
        width: 3,
        height: 3,
        placement: "block",
        color: "#4b5563",
        icon: "🌾",
    },    {
        id: "mill-4x3",
        name: "Mill",
        itemType: "building",
        width: 4,
        height: 3,
        placement: "block",
        color: "#374151",
        icon: "🍃",
    },    {
        id: "well-3x3",
        name: "Well",
        itemType: "building",
        width: 3,
        height: 3,
        placement: "block",
        color: "#1e3a8a",
        icon: "🪣",
    },
    {
        id: "fish-pond-5x5",
        name: "Fish Pond",
        itemType: "building",
        width: 5,
        height: 5,
        placement: "block",
        color: "#1e40af",
        icon: "🐟",
    },    {
        id: "insect-house-5x5",
        name: "Insect House",
        itemType: "building",
        width: 5,
        height: 5,
        placement: "block",
        color: "#4b0000",
        icon: "🪲",
    },
    {
        id: "shed-9x9",
        name: "Shed",
        itemType: "building",
        width: 9,
        height: 9,
        placement: "block",
        color: "#374151",
        icon: "🛖",
    },
];
